# -*- coding: utf-8 -*-
"""Q18_P3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KuTM8wPIiVXPjumhpAVvW0z0J_wFgrg5
"""

!pip install -q outlines transformers accelerate sentencepiece

import torch
import outlines
from transformers import AutoTokenizer, AutoModelForCausalLM
from pydantic import BaseModel

MODEL_NAME = "Qwen/Qwen3-4B-Instruct-2507"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
hf_model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto",
    torch_dtype="auto"
)

model = outlines.from_transformers(hf_model, tokenizer)

class PlannerOutput(BaseModel):
    thought: str
    is_done: bool
    response: str

def run_planner(user_prompt: str):
    prompt = f"""
You are a planner for a CSV data-analysis agent.

Return a JSON object with exactly these fields:
- thought: brief reasoning
- is_done: true if the task is complete, false otherwise
- response: next instruction if not done, or final formatted answer if done

User request: {user_prompt}
"""
    result = model(prompt, PlannerOutput, max_new_tokens=120)
    print(result)
    print("-" * 60)
    return result

prompts = [
    "Load the CSV and inspect the column names.",
    "Check whether the Fare column exists, then compute its mean.",
    "Filter rows where Age > 30 and count them.",
    "The mean Fare is 34.65, so provide the final formatted answer.",
    "We already computed the answer @mean_fare[34.65]. Return the final answer now."
]

outputs = [run_planner(p) for p in prompts]

from google.colab import drive
drive.mount('/content/drive')

import json
import os

BASE_PATH = "/content/drive/MyDrive/Project 3"

print("Checking folder:", BASE_PATH)
print(os.listdir(BASE_PATH))

SELECTED_IDS = [0, 5, 9, 10, 14, 18, 24, 25, 26, 55]

with open(f"{BASE_PATH}/da-dev-questions.jsonl") as f:
    questions = [json.loads(line) for line in f]

tasks = [questions[i] for i in SELECTED_IDS]

for t in tasks:
    print(t["question"])

from pydantic import BaseModel

class PlannerOutput(BaseModel):
    thought: str
    is_done: bool
    response: str

def planner_step(prompt):
    json_string_result = model(prompt, PlannerOutput, max_new_tokens=800)
    parsed_dict = json.loads(json_string_result)
    return PlannerOutput(**parsed_dict)

def coder(instruction, question, table_path, constraints="", output_format=""):
    prompt = f"""
Write executable Python code only.

Use:
import pandas as pd
df = pd.read_csv("{table_path}")
df.columns = df.columns.str.strip()

Question: {question}

Rules:
- Match columns case-insensitively
- If exact lowercase name is missing, search for the closest matching column from df.columns
- The final answer must be valid Python
- Store final formatted answer in a variable named result
- Always print(result)
- Never output raw text like @mean_fare[...]
- No markdown
- No explanations
"""
    return str(model(prompt, max_new_tokens=400))

def clean_code(code: str) -> str:
    code = str(code)
    code = code.replace("```python", "").replace("```", "").strip()
    return code

import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/Project 3/da-dev-tables/test_ave.csv")
df.columns = df.columns.str.strip()

fare_col = next((col for col in df.columns if col.lower() == "fare"), None)
if fare_col is None:
    fare_col = next((col for col in df.columns if "fare" in col.lower()), None)
if fare_col is None:
    raise ValueError(f"Fare column not found. Columns: {list(df.columns)}")

result = f"@mean_fare[{pd.to_numeric(df[fare_col], errors='coerce').mean():.2f}]"
print(result)

def executor(code):
    code = clean_code(code).strip()

    if code.startswith("@"):
        return None, "Model returned a raw answer tag instead of Python code.", code

    buffer = io.StringIO()
    local_env = {}

    try:
        with contextlib.redirect_stdout(buffer):
            exec(code, {"pd": pd}, local_env)

        output = buffer.getvalue().strip()
        if "result" in local_env:
            return str(local_env["result"]), None, code
        return output, None, code

    except Exception as e:
        return None, str(e), code

import pandas as pd

path = "/content/drive/MyDrive/Project 3/da-dev-tables/unemployement_industry.csv"
df = pd.read_csv(path)
print(df.head())
print(df.columns.tolist())

def observer(raw_output, error):
    if error:
        return f"Error occurred: {error}"
    else:
        return f"Execution result: {raw_output}"

def get_table_path(task):
    return f"/content/drive/MyDrive/Project 3/da-dev-tables/{task['file_name']}"

MAX_STEPS = 5

def run_agent(task):
    history = ""
    question = task["question"]
    table_path = get_table_path(task)

    print("USING TABLE PATH:", table_path)

    for step in range(MAX_STEPS):
        print(f"\nSTEP {step+1}")

        planner_prompt = f"""
You are a planner for a CSV data-analysis agent.

Question: {question}
CSV path: {table_path}
Constraints: {task.get('constraints', '')}
Required output format: {task.get('format', '')}

History:
{history}

Return JSON with:
- thought
- is_done
- response

Keep the response short.
If enough information is available, finish.
"""
        plan = planner_step(planner_prompt)
        print("PLAN:", plan)

        if plan.is_done:
            return plan.response

        code = coder(
            plan.response,
            question,
            table_path,
            task.get("constraints", ""),
            task.get("format", "")
        )

        output, error, cleaned_code = executor(code)

        print("CODE:\n", cleaned_code)

        obs = f"Execution error: {error}" if error else f"Execution result: {output}"
        print("OBSERVATION:", obs)

        history += f"""
Instruction: {plan.response}
Code:
{cleaned_code}
Observation: {obs}
"""

    return "max steps reached"

results = []

for t in tasks:
    print("QUESTION:", t["question"])
    answer = run_agent(t)
    print("FINAL:", answer)
    print("="*60)
    results.append(answer)

import os

print("cwd:", os.getcwd())
print("da-dev-tables exists:", os.path.exists("da-dev-tables"))

if os.path.exists("da-dev-tables"):
    print(os.listdir("da-dev-tables")[:20])

import os

print("Drive mounted:", os.path.exists("/content/drive"))
print("MyDrive exists:", os.path.exists("/content/drive/MyDrive"))

if os.path.exists("/content/drive/MyDrive"):
    print(os.listdir("/content/drive/MyDrive")[:50])

print(os.listdir("/content/drive/MyDrive/Project 3"))

print(os.listdir("/content/drive/MyDrive/Project 3/da-dev-tables")[:20])